<?php
/**
 * @file
 *
 * This file is part of ding_social module.
 *
 * ding_social module is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * ding_social module is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with ding_social module. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function ding_social_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_theme().
 */
function ding_social_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['ding_social__instagram_block'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'ding-social--instagram-block',
    'path' => drupal_get_path('module', 'ding_social') . '/templates',
  );

  $theme['ding_social__instagram_block_item'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'ding-social--instagram-block-item',
    'path' => drupal_get_path('module', 'ding_social') . '/templates',
  );

  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ding_social_preprocess_instagram_block(&$variables) {
  $variables['theme_hook_suggestions'] = array('ding_social__instagram_block');

  $block_config = variable_get('instagram_block_user_block_settings', array());
  if (!empty($block_config['title'])) {
    $variables['block_title'] = $block_config['title'];
  }

  $variables['content']['#attached'] = array(
    'js' => array(
      libraries_get_path('slick') . '/slick/slick.min.js',
      drupal_get_path('module', 'ding_social') . '/js/ding_social.js',
    ),
    'css' => array(
      libraries_get_path('slick') . '/slick/slick.css',
      libraries_get_path('slick') . '/slick/slick-theme.css',
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ding_social_preprocess_instagram_block_image(&$variables) {
  $variables['theme_hook_suggestions'] = array('ding_social__instagram_block_item');
  if ($variables['caption'] == 'Instagram image, no caption provided by author.') {
    $variables['caption'] = '';
  }
}
