<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_theme().
 */
function ding_social_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['ding_social__instagram_block'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'ding-social--instagram-block',
    'path' => drupal_get_path('module', 'ding_social') . '/templates',
  );

  $theme['ding_social__instagram_block_item'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'ding-social--instagram-block-item',
    'path' => drupal_get_path('module', 'ding_social') . '/templates',
  );

  return $theme;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ding_social_preprocess_instagram_block(&$variables) {
  $variables['theme_hook_suggestions'] = array('ding_social__instagram_block');
  $variables['content']['#attached'] = array(
    'js' => array(
      libraries_get_path('slick') . '/slick/slick.min.js',
      drupal_get_path('module', 'ding_social') . '/js/ding_social.js',
    ),
    'css' => array(
      libraries_get_path('slick') . '/slick/slick.css',
      libraries_get_path('slick') . '/slick/slick-theme.css',
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ding_social_preprocess_instagram_block_image(&$variables) {
  $variables['theme_hook_suggestions'] = array('ding_social__instagram_block_item');
  if ($variables['caption'] == 'Instagram image, no caption provided by author.') {
    $variables['caption'] = '';
  }
}
